spring:
  application:
    name: TDTD

  # 기본 프로파일 설정 (로컬 개발 환경)
  profiles:
    active: local

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/TDTD?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username:
#    password:

  # JPA 공통 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# 공통 로깅 설정
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    com.todaktodot.TDTD: info

# 에러 응답 설정 (개발 환경)
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never

oauth:
  apple:
    url:
      auth: https://appleid.apple.com/auth/token
    client-id: tdtd
    login-key: tdtd
    team-id: tdtd
    key-path: tdtd

jwt:
  secret-key: b5061bc39cd8d5efcc97ee7e6b2569f65fc49ad7eea119964db7e8e7e36ab4452a96396c5fd868e83442491b4787fbc07be19ba3bc55f1c28a01250dbff078f7
