-- AI 프롬프트 템플릿 테이블
CREATE TABLE AI_PROMPT (
    PROMPT_ID       BIGINT          NOT NULL AUTO_INCREMENT COMMENT '프롬프트 ID (PK)',
    PROMPT_NAME     VARCHAR(100)    NOT NULL COMMENT '프롬프트 이름',
    PROMPT_DESC     VARCHAR(500)    NULL COMMENT '프롬프트 설명',
    PROMPT_CONTENT  TEXT            NOT NULL COMMENT '프롬프트 내용',
    VERSION         INT             NOT NULL DEFAULT 1 COMMENT '버전',
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (PROMPT_ID),
    UNIQUE KEY UK_PROMPT_NAME_VERSION (PROMPT_NAME, VERSION, DEL_YN),
    INDEX IDX_PROMPT_NAME (PROMPT_NAME, USE_YN, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 프롬프트 템플릿';

-- 예시 상황 카테고리 테이블
CREATE TABLE SITUATION_CATEGORY (
    CATEGORY_ID     BIGINT          NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID (PK)',
    SUBJECT         VARCHAR(20)     NOT NULL COMMENT '질문 주제 (LOVE, ECONOMY, LIFESTYLE)',
    CATEGORY_NAME   VARCHAR(50)     NOT NULL COMMENT '카테고리명 (예: 기념일/이벤트)',
    CATEGORY_DESC   VARCHAR(200)    NULL COMMENT '카테고리 설명',
    SORT_ORDER      INT             NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (CATEGORY_ID),
    INDEX IDX_SUBJECT (SUBJECT, USE_YN, DEL_YN),
    INDEX IDX_SORT_ORDER (SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='예시 상황 카테고리';
