-- 커플 연결 코드 인증 테이블
CREATE TABLE COUPLE_LINK_AUTH (
    COUPLE_LINK_AUTH_SEQ BIGINT          NOT NULL AUTO_INCREMENT COMMENT '커플 연결 인증 SEQ (PK)',
    LINK_CODE            VARCHAR(50)     NOT NULL COMMENT '연결 코드 (6자리 영문대문자+숫자)',
    ISSUED_USER_ID       VARCHAR(50)     NOT NULL COMMENT '코드 발급자 ID',
    LINKED_USER_ID       VARCHAR(50)     NULL     COMMENT '연결된 사용자 ID',
    STATUS               VARCHAR(20)     NOT NULL COMMENT '상태 (ISSUED, EXPIRED, LINKED)',
    EXPIRED_DT           DATETIME        NOT NULL COMMENT '만료 일시',
    REG_DT               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID              VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID              VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN               CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (COUPLE_LINK_AUTH_SEQ),
    UNIQUE KEY UK_LINK_CODE (LINK_CODE, DEL_YN),
    INDEX IDX_ISSUED_USER_ID (ISSUED_USER_ID, DEL_YN),
    INDEX IDX_STATUS (STATUS, DEL_YN),
    INDEX IDX_EXPIRED_DT (EXPIRED_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='커플 연결 코드 인증';