-- 커플 발급 데일리카드 테이블
CREATE TABLE COUPLE_DAILY_CARD (
    COUPLE_CARD_ID      BIGINT          NOT NULL AUTO_INCREMENT COMMENT '커플 데일리카드 ID (PK)',
    COUPLE_ID           BIGINT          NOT NULL COMMENT '커플 ID (FK)',
    CARD_ID             BIGINT          NOT NULL COMMENT '데일리카드 ID (FK)',
    ISSUED_DATE         DATE            NOT NULL COMMENT '발급 일자',
    SELECTED_TYPE       VARCHAR(20)     NULL COMMENT '선택된 유형 (ROLEPLAY, BALANCE) - NULL이면 미선택',
    SELECTED_BY_USER_ID VARCHAR(50)     NULL COMMENT '유형 선택한 사용자 ID',
    REG_DT              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID             VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID             VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN              CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (COUPLE_CARD_ID),
    UNIQUE KEY UK_COUPLE_ISSUED_DATE (COUPLE_ID, ISSUED_DATE, DEL_YN),
    INDEX IDX_COUPLE_ID (COUPLE_ID, DEL_YN),
    INDEX IDX_CARD_ID (CARD_ID, DEL_YN),
    INDEX IDX_ISSUED_DATE (ISSUED_DATE, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='커플 발급 데일리카드';
