-- 데일리카드 질문 항목 테이블
CREATE TABLE DAILY_CARD_QUESTION (
    CARD_ID         BIGINT          NOT NULL COMMENT '데일리카드 ID (PK, FK)',
    QUESTION_NO     INT             NOT NULL COMMENT '질문 번호 (PK)',
    QUESTION_TYPE   VARCHAR(20)     NOT NULL COMMENT '질문 유형 (MULTIPLE_CHOICE, SUBJECTIVE)',
    ANSWER_REQ_YN   CHAR(1)         NOT NULL DEFAULT 'Y' COMMENT '답변 필수 여부 (Y/N)',
    QUESTION_CNTS   VARCHAR(1000)   NOT NULL COMMENT '질문 내용',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (CARD_ID, QUESTION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='데일리카드 질문 항목';
