-- 데일리카드 사용자 답변 테이블
CREATE TABLE DAILY_CARD_USER_ANSWER (
    ANSWER_ID           BIGINT          NOT NULL AUTO_INCREMENT COMMENT '답변 ID (PK)',
    COUPLE_CARD_ID      BIGINT          NOT NULL COMMENT '커플 데일리카드 ID (FK)',
    CARD_ID             BIGINT          NOT NULL COMMENT '데일리카드 ID (FK)',
    QUESTION_NO         INT             NOT NULL COMMENT '질문 번호 (FK)',
    USER_ID             VARCHAR(50)     NOT NULL COMMENT '답변 사용자 ID',
    ANSWER_CONTENT      VARCHAR(2000)   NOT NULL COMMENT '답변 내용 (객관식: OPTION_NO, 주관식: 텍스트)',
    REG_DT              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID             VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID             VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN              CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (ANSWER_ID),
    UNIQUE KEY UK_COUPLE_CARD_QUESTION_USER (COUPLE_CARD_ID, CARD_ID, QUESTION_NO, USER_ID, DEL_YN),
    INDEX IDX_COUPLE_CARD_ID (COUPLE_CARD_ID, DEL_YN),
    INDEX IDX_USER_ID (USER_ID, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='데일리카드 사용자 답변';
