-- 데일리카드 객관식 선택지 테이블
CREATE TABLE DAILY_CARD_OPTION (
    CARD_ID         BIGINT          NOT NULL COMMENT '데일리카드 ID (PK, FK)',
    QUESTION_NO     INT             NOT NULL COMMENT '질문 번호 (PK, FK)',
    OPTION_NO       INT             NOT NULL COMMENT '선택지 번호 (PK)',
    OPTION_CNTS     VARCHAR(500)    NOT NULL COMMENT '선택지 내용',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (CARD_ID, QUESTION_NO, OPTION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='데일리카드 질문 문항';
