-- 데일리카드 콘텐츠 테이블
CREATE TABLE DAILY_CARD (
    CARD_ID         BIGINT          NOT NULL AUTO_INCREMENT COMMENT '데일리카드 ID (PK)',
    MODE            VARCHAR(20)     NOT NULL COMMENT '질문 모드 (DESSERT, COFFEE, WHISKEY)',
    SUBJECT         VARCHAR(20)     NOT NULL COMMENT '질문 주제 (LOVE, ECONOMY, LIFESTYLE)',
    TYPE            VARCHAR(20)     NOT NULL COMMENT '질문 유형 (ROLEPLAY, BALANCE)',
    CARD_TITLE      VARCHAR(500)    NOT NULL COMMENT '메인 질문/상황 설명',
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         VARCHAR(50)     NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         VARCHAR(50)     NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (CARD_ID),
    INDEX IDX_CARD_SEARCH (DEL_YN, USE_YN, MODE, SUBJECT, TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='데일리카드';
