-- 사용자 작성 정지 테이블
CREATE TABLE USER_SUSPENSION (
    SUSPENSION_ID   BIGINT          NOT NULL AUTO_INCREMENT COMMENT '정지 ID (PK)',
    USER_ID         BIGINT          NOT NULL COMMENT '대상 사용자 ID (FK)',
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'SUSPENDED' COMMENT '정지 상태 (SUSPENDED, RELEASED)',
    SUSPENDED_DT    DATETIME        NOT NULL COMMENT '정지 일시',
    RELEASED_DT     DATETIME        NULL COMMENT '해제 일시',
    NOTICE_ACK_YN   CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '정지 안내 팝업 확인 여부 (Y/N)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    ACTIVE_SLOT     INT             GENERATED ALWAYS AS (CASE WHEN STATUS = 'SUSPENDED' AND DEL_YN = 'N' THEN 1 ELSE NULL END) VIRTUAL COMMENT '활성 row 유니크 제약용 슬롯',
    PRIMARY KEY (SUSPENSION_ID),
    UNIQUE KEY UK_USER_ACTIVE (USER_ID, ACTIVE_SLOT),
    INDEX IDX_USER_STATUS (USER_ID, STATUS, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자 작성 정지';
