-- 투표 답변 항목 테이블
CREATE TABLE VOTE_OPTION (
    OPTION_ID       BIGINT          NOT NULL AUTO_INCREMENT COMMENT '답변 항목 ID (PK)',
    VOTE_ID         BIGINT          NOT NULL COMMENT '투표 ID (FK)',
    SORT_ORDER      INT             NOT NULL COMMENT '표시 순서 (1~5)',
    CONTENT         VARCHAR(20)     NOT NULL COMMENT '답변 내용',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (OPTION_ID),
    INDEX IDX_VOTE_ID (VOTE_ID, DEL_YN, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='투표 답변 항목';
