-- 투표 좋아요 테이블
CREATE TABLE VOTE_LIKE (
    LIKE_ID         BIGINT          NOT NULL AUTO_INCREMENT COMMENT '좋아요 ID (PK)',
    VOTE_ID         BIGINT          NOT NULL COMMENT '투표 ID (FK)',
    USER_ID         BIGINT          NOT NULL COMMENT '좋아요한 사용자 ID (FK)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    ACTIVE_SLOT     INT             GENERATED ALWAYS AS (CASE WHEN DEL_YN = 'N' THEN 1 ELSE NULL END) VIRTUAL COMMENT '활성 row 유니크 제약용 슬롯',
    PRIMARY KEY (LIKE_ID),
    UNIQUE KEY UK_VOTE_USER_ACTIVE (VOTE_ID, USER_ID, ACTIVE_SLOT),
    INDEX IDX_VOTE_ID (VOTE_ID, DEL_YN),
    INDEX IDX_USER_ID (USER_ID, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='투표 좋아요';
