-- 투표 신고 테이블
CREATE TABLE VOTE_REPORT (
    REPORT_ID       BIGINT          NOT NULL AUTO_INCREMENT COMMENT '신고 ID (PK)',
    VOTE_ID         BIGINT          NOT NULL COMMENT '신고 대상 투표 ID (FK)',
    USER_ID         BIGINT          NOT NULL COMMENT '신고자 사용자 ID (FK)',
    REASON          VARCHAR(20)     NOT NULL COMMENT '신고 사유 (ABUSE, OBSCENE, SPAM, ADVERTISEMENT, PRIVACY, ILLEGAL, DISLIKE)',
    REG_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REGR_ID         BIGINT          NOT NULL COMMENT '등록자 ID',
    UPD_DT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    UPDR_ID         BIGINT          NOT NULL COMMENT '수정자 ID',
    DEL_YN          CHAR(1)         NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y/N)',
    PRIMARY KEY (REPORT_ID),
    UNIQUE KEY UK_VOTE_USER (VOTE_ID, USER_ID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_VOTE_ID (VOTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='투표 신고';
